name: multi_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.2
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
