name: multi_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  go_router: ^14.0.2
  google_sign_in: ^6.2.1
  intl: null
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  particles_fly: ^0.0.8
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.2
  toastification: ^2.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
flutter_intl:
  enabled: true
  class_name: S
  main_locale: es,en
